language: java

jdk: 
    -openjdk8

addons:
    sonarcloud:
     organization: "luca-zm"
     token:
        secure: "5a1f8f6260853ceae464c5b4aedb1f333f15b0de"

script:
- ant build
- sonar-scanner
