language: java

jdk: 
    -openjdk8

addons:
    sonarcloud:
     organization: "luca-zm"
     token:
        secure: "6d9b291d5687d1465320d95b2e166fffc2738c41"

script:
- ant build
- sonar-scanner
