dist: xenial
language: java
jdk:
    -openjdk13
addons:
  apt:
    packages:
      - ant 
  sonarcloud:
    organization: <nome> 
    token:      
      secure: "<token>"
script:
- ant build
- sonar-scanner
