package logic.Model;

public class Transaction {
	private String date;
	private int productId;
	private String productName;
	private int value;
	
	//Normal Constructor
	public Transaction(String date, int productId, String productName, int value) {
		this.date = date;
		this.productId = productId;
		this.productName = productName;
		this.value = value;
	}
	
	//Bonus Constructor, generated by BonusMachine
	public Transaction(String date,  int value) {
		this.date = date;
		this.productId = 0;
		this.productName = null;
		this.value = value;
		
	}

	public String getDate() {
		return date;
	}

	public int getProductId() {
		return productId;
	}

	public String getProductName() {
		return productName;
	}

	public int getValue() {
		return value;
	}

	@Override
	public String toString() {
		return "Transaction [date=" + date + ", productId=" + productId + ", productName=" + productName + ", value="
				+ value + "]";
	}
	
	

}
