language: java
jdk: 
    -openjdk8

addons:
    sonarcloud:
     organization: "luca-zm1"
     token:
        secure: "cfd7a6e7d54167269adc92c857f7b7f4606fe19e"

script:
- ant build
- sonar-scanner

